### ISSUE TITLE
论文代码

### ISSUE THREAD

**Issue by xiamenwcy** [sfzhang15/SFD#1]
你好，请问一下论文代码何时放出？

**Comment by takecareofbigboss** [comment]
Your iccv paper write "the code will be available to the research community",Want to know the specific time u ll release ur code, thks ~

**Comment by zhang365947064** [comment]
Recently we are busy with the next working and time is a bit tense. So the code may be compiled and published one months later. Sorry about that.

**Comment by takecareofbigboss** [comment]
@zhang365947064  hi any update in the next few days?

**Comment by sfzhang15** [comment]
@takecareofbigboss Hi, the code will be compiled and published after 15.11.2017. Sorry about that.

**Comment by MengXinChengXuYuan** [comment]
@sfzhang15 you promise right? I've been looking forward to it for quite long...

**Comment by MengXinChengXuYuan** [comment]
@sfzhang15  Hi, any updates?

**Comment by sfzhang15** [comment]
@MengXinChengXuYuan 
Code has been updated.

**Comment by chinakook** [comment]
Excellent.

**Comment by MengXinChengXuYuan** [comment]
@xiamenwcy Thank you very much for kindly sharing your code!
I know this may be too much, but is there any possibility that you also share your training part of your whole work ?

**Comment by Edwardmark** [comment]
@sfzhang15 Thank you very much for kindly sharing your code!
I know this may be too much, but is there any possibility that you also share your training part of your whole work ?
