### ISSUE TITLE
Can't find the codes that related to stage2 of anchor matching strategy

### ISSUE THREAD

**Issue by Duankaiwwen** [sfzhang15/SFD#11]
Hi@sfzhang15, thanks for your amazing contribution! In section 3.2, stage 2, this paper says "firstly picking
out anchors whose jaccard overlap with this face are higher than 0.1, then sorting them to select top-N as
matched anchors of this face". But I didn't find the corresponding code, could you please tell me how to implement the stage2 with code？

**Comment by sfzhang15** [comment]
@Duankaiwwen Hi, you can modify the 'MatchBBox' function in bbox_util.cpp  by adding extra stage to implement the stage 2 of anchor matching strategy.

**Comment by Duankaiwwen** [comment]
Thank you for your reply. Does this mean that you didn't release the complete version? So, if I don't modify the 'MatchBBox' function, I won't achieve the results described in your paper by my own training model, right? How much does stage 2 affect the result?

**Comment by sfzhang15** [comment]
@Duankaiwwen 
Sorry about that because of the limitations of my boss's company.
The stage 2 can be implemented with a little modification for 'MatchBBox' function, you can try to implement it.
The affect of Stage 2 can be referred to Table 1 in our paper.

**Comment by Duankaiwwen** [comment]
I understand. Thank you very much!
