### ISSUE TITLE
max-out background label

### ISSUE THREAD

**Issue by shz0519** [sfzhang15/SFD#13]
Hi!
In test phase，do you apply the max-out background label for the conv3 3 detection layer?thank you!

**Comment by MengXinChengXuYuan** [comment]
No, it's only for train phase, I suppose

**Comment by sfzhang15** [comment]
@shz0519 @MengXinChengXuYuan Hi, the max-out background label is used for the conv3_3 at train and test phase, you can refer to the prototxt file. The max-out background label predicts background label multi times and selects the highest one before softmax operation.

**Comment by shz0519** [comment]
OK ,thank you！in order to implement the data augmentation in your paper, Do you just modify the 'SampleBBox' functions which makes the ratio of face is 1:1？need to modify other code?

**Comment by sfzhang15** [comment]
Yes

**Comment by jianyin2016** [comment]
Should I re-compile the original caffe project after some contents  been edited such as lines within the SampleBBox function to use the changes? @sfzhang15

**Comment by sfzhang15** [comment]
@jianyin2016 You better recompile it using 'make all -j &7 make py'.
