### ISSUE TITLE
尺寸大小问题

### ISSUE THREAD

**Issue by Jacky3213** [sfzhang15/SFD#14]
非常感谢您分享的成果。在研究过程中遇到了一些问题需要请教一下。我没有修改代码直接进行训练的，从测试的效果来看还不错。在研究代码的过程中我发现一个问题，代码中将网络reshape到了输入图像的大小，而不是将图像resize到网络输入的大小。我对两种情况进行了对比测试，发现效果差不多，但后者速度是前者的5倍左右。愿闻其详，谢谢！

**Comment by sfzhang15** [comment]
@Jacky3213 “代码中将网络reshape到了输入图像的大小，而不是将图像resize到网络输入的大小”，能否再解释一下这句话？ 
caffe在前向传播的时候，会先用预先定义的输入大小（如640x640），来初始化整个网络。等真正的图片输入进来后，整个网络会再次被reshape到对应大小。不知道你说的是这个问题吗？

**Comment by Jacky3213** [comment]
@sfzhang15  重新测试一下，对于1080*1920的视频来说，reshape 网络输入大小至（1，3，1920，1080）的效果比将image resize至（640，640）的效果要好，但后者的速度是前者的5倍左右，也就是牺牲精度换速度，但即使这样，后者的效果也还是不错的。

**Comment by sfzhang15** [comment]
@Jacky3213 
由于SFD是全卷积网络，所以输入可以是任意大小，训练的时候搞成640x640是为了多个图像一起输入。
我们测试时都不改变图像的比例，是为了不改变人脸的比例。
由于训练大小是640x640，所以SFD的检测范围是(8, 640)，因此可以根据这个来缩放图像，以平衡精度和速度。
大输入速度一定慢，但效果不一定好，因为可能放太大了，超过了检测器的检测范围。

**Comment by Jacky3213** [comment]
@sfzhang15 受教了，多谢！

**Comment by kli-nlpr** [comment]
@sfzhang15  由于训练大小是640x640，所以SFD的检测范围是(8, 640) ，，为什么是这个范围？

**Comment by sfzhang15** [comment]
@kli-nlpr 由于训练大小是640x640，所以最大人脸就是640，因此上限是640；训练中，长或宽小于一定大小的，我们会滤掉，比如6，因此保守估计，下限是8。

**Comment by wywywy01** [comment]
请问下,过滤一定长宽大小的代码,是在哪一部分

**Comment by sfzhang15** [comment]
@wywywy01 
可以在annotation_data_layer中或MeetEmitConstraint函数中实现。

**Comment by wywywy01** [comment]
请问下这个layer的convolution_param 里面num_output: 4是一个尺寸1*2(种类)加上2么,是什么具体的意思呢
![image](https://user-images.githubusercontent.com/22450352/41162006-236907be-6b67-11e8-963f-85047ef7d8a1.png)

**Comment by wywywy01** [comment]
谢谢作者的耐心解答,我还有个小问题
如果我想检测640*640图片5*5左右的物体的话,仅仅修改conv3_3相关的feature map的anchor scale和min_size和max_size可以吗?
我不确定要不要去修改您说的过滤小尺寸长款的代码(不太熟悉),我想问下是我按照你的github 下面提示安装编译caffe的ssd分支,它里面默认过滤了小尺寸的物体吗?

附图:修改的conv3_3
layer {
  name: "conv3_3_norm_mbox_loc"
  type: "Convolution"
  bottom: "conv3_3_norm"
  top: "conv3_3_norm_mbox_loc"
  param {
    lr_mult: 1
    decay_mult: 1
  }
  param {
    lr_mult: 2
    decay_mult: 0
  }
  convolution_param {
    num_output: 24
    pad: 1
    kernel_size: 3
    stride: 1
    weight_filler {
      type: "xavier"
    }
    bias_filler {
      type: "constant"
      value: 0
    }
  }
}
...
layer {
  name: "conv3_3_norm_mbox_conf"
  type: "Convolution"
  bottom: "conv3_3_norm"
  top: "conv3_3_norm_mbox_conf"
  param {
    lr_mult: 1
    decay_mult: 1
  }
  param {
    lr_mult: 2
    decay_mult: 0
  }
  convolution_param {
    num_output: 14
    pad: 1
    kernel_size: 3
    stride: 1
    weight_filler {
      type: "xavier"
    }
    bias_filler {
      type: "constant"
      value: 0
    }
  }
}
...
layer {
  name: "conv3_3_norm_mbox_priorbox"
  type: "PriorBox"
  bottom: "conv3_3_norm"
  bottom: "data"
  top: "conv3_3_norm_mbox_priorbox"
  prior_box_param {
    min_size: 8
    max_size: 16
    aspect_ratio: 1.2
    aspect_ratio: 0.9
    flip: true
    clip: true
    variance: 0.1
    variance: 0.1
    variance: 0.2
    variance: 0.2
    step: 4
    offset: 0.5
  }
}

**Comment by sfzhang15** [comment]
@wywywy01 
1. The output in the conf layer is num_anchors * num_classes and the output in the loc layer is num_anchors * 4 (AGNOSTIC)
2. 如果想在640x640图片上检55左右的物体，可以不使用conv3_3，直接从conv4_3开始
3. SSD原始代码里头，没有过滤小尺寸物体

**Comment by wywywy01** [comment]
好的,非常谢谢
我说错了是5乘5的物体
