### ISSUE TITLE
About fddb_from_rectangle_to_ellipse

### ISSUE THREAD

**Issue by daodao316** [sfzhang15/SFD#18]
Can you explain the parameters in 'Fit.mat' in fddb_from_rectangle_to_ellipse? and how to train the w? Thank you very much

**Comment by sfzhang15** [comment]
@daodao316 
After evaluated on FDDB, some bboxes have been true positives. These TPs have their corresponding gt ellipses. Using these TP bboxes and their gt ellipses, you can obtain the **w**, which is the coefficients from rectangle to ellipse.

**Comment by daodao316** [comment]
Thank you
