### ISSUE TITLE
how to get square patch when testing

### ISSUE THREAD

**Issue by NickMinYang** [sfzhang15/SFD#2]
In the paper, "one is the biggest square patch, and the size of the other four square patches range between [0.3, 1] of the short size of the original image."

When training, you can get square patch, but how to get square patch when testing.
WARP?FIT_SMALL_SIZE?or FIT_LARGE_SIZE_AND_PAD?

**Comment by NickMinYang** [comment]
@sfzhang15

**Comment by zhang365947064** [comment]
At testing, we do not change the ratio of image. We directly test the original image, or we zoom in/out  the image to test.

**Comment by NickMinYang** [comment]
use mult-scale?
@sfzhang15

**Comment by zhang365947064** [comment]
For AFW, PASCAL face and FDDB dataset, we just use single scale. For WIDER FACE dataset, we use multi-scale testing.

**Comment by NickMinYang** [comment]
OK, Thanks for your reply!
@sfzhang15

**Comment by DL-85** [comment]
@NickMinYang @sfzhang15 
What is multi-scale testing and how to do it? 
When I try to implement it，I resize the image to 2×w and 2×h， then the error ”Check failed: shape[i] <= 0x7fffffff / count_ (1536 vs. 1526) blob size exceeds INT_MAX“. I guess it is beacause the image in WIDER FACE is too large to double. 
What are scales that you choose in multi-scale testing?

**Comment by sfzhang15** [comment]
@DL-85 
We use one 12G TITAN X to test our detector. There are some details on the multi-scale testing used for WIDER faces:
0) According to the image size and the GPU memory, computing the largest input size of the original image.
1) if the largest input size > the original image size
    a) testing the original image
    b) flipping the original image and testing it
    c) shrinking the original image by half and testing it
    d) gradually enlarging the original image twice and testing it until enlarging to the largest image.
2) if the largest input size < the original image size
    a) testing the largest image
    b) flipping the largest image and testing it.
    c) shrinking the largest image by 0.75 and testing it.
    d) shrinking the largest image by half and testing it.

**Comment by DL-85** [comment]
@sfzhang15 
I use the 11G 1080Ti. The original image size is ok for the detector, but when I enlarge the original double, I met this error "Check failed: shape[i] <= 0x7fffffff / count_ (1536 vs. 1526) blob size exceeds INT_MAX" and the gpu memory used is 5.6G which is far to be full.
I google this error and find it may be the caffe limit for input image size.
Did you meet this error and how do you solve it? For example, the image "1_Handshaking_Handshaking_1_35.jpg" in WIDER_val  is 1024*1392, the original size is ok,  enlarge whill met the error and how to do next?

**Comment by sfzhang15** [comment]
@DL-85 
According to the error information "shape[i] <= 0x7fffffff / count_ (1536 vs. 1526)", you can compute the max input size of the original image. Specifically, in our TITAN X GPU, we us max_input_size = sqrt(0x7fffffff / 577 / ori_img_w / ori_img_h).

**Comment by NickMinYang** [comment]
In multi_scale_test, the thresholds are 30 and 100? And in bbox_vote, the iou threshold is 0.3, Why? @sfzhang15

**Comment by sfzhang15** [comment]
@NickMinYang Hi,  the threshold 30 is for the reduced scale testing, because we reduce the image in order to detect large faces.  The threshold 100 is for the magnified scale testing, because we enlarge the image in order to detect small faces. The IOU threshold 0.3 in bbox_vot is to be consistent with the IOU threshold of single scale testing.

**Comment by NickMinYang** [comment]
@sfzhang15 
I mean:
why 30, not 32? 
why 100, not 128?

**Comment by sfzhang15** [comment]
@NickMinYang 
Both of them are empirical setting and you can change them. We think 30 Vs 32, 100 Vs 128，they may not be much different.

**Comment by NickMinYang** [comment]
@sfzhang15
Ok,Thanks!

**Comment by hdjsjyl** [comment]
@sfzhang15 , how to compute the max size of image for caffe? What is the equation? Thanks

**Comment by sfzhang15** [comment]
@hdjsjyl 
Hi, the blob max_size is **0x7fffffff**. As for VGG16, the biggest blob appear on CONV1_2‘s bias term, which blob size is (**num-channel * kennel-size * kennel-size**) * **img-height** * **img-width** = (64*3*3) * img-height * img-width = 576 * img-height * img-width. So the max size of image for VGG16 in caffe is compute by **sqrt(0x7fffffff / 576 / img-height/ img-width)**, since there is sqrt operation, so we use sqrt(0x7fffffff / **577** / img-height/ img-width) to avoid errors.

**Comment by sfzhang15** [comment]
@hdjsjyl 
For different network, the biggest blob is different. Our suggestion is that according to the error information, e.g., "shape[i] <= 0x7fffffff / count_ (1536 vs. 1526)", to estimate the max size of image.  As for our equation, there only one parameter need to be estimated, i.e., sqrt(0x7fffffff / **X** / img-height/ img-width).
