### ISSUE TITLE
Question about data augmentation

### ISSUE THREAD

**Issue by abdelrahman-gaber** [sfzhang15/SFD#20]
Hi, 
You mentioned about modifying the data augmentation code of SSD to make sure that it does not change the image ratio. I have some questions about this point; first, during training process each image is resized to 640x640, this itself changes the image size ratio as input images are not all square images as far as I know. Are you doing any trick here to avoid this, or it is true that image ratio changes while resizing ?

Second question, Which code should we change to do this modification in augmentation ? Do we just do the change at the beginning of train.prototxt in the sampler part and specify:
min_aspect_ratio: 1.0
max_aspect_ratio: 1.0

or we need to change any C++ function in Caffe ?

Thanks in advance.

**Comment by sfzhang15** [comment]
@abdelrahman-gaber Hi,
As you said,  each cropped image is resized to 640x640, so you should guarantee that the cropped image from the original image is square, only in this way the image ratio will not be changed.
To achieve this goal, you should change c++ function in sampler.cpp.

**Comment by abdelrahman-gaber** [comment]
It is clear now. Thank you.

**Comment by whcjb** [comment]
@abdelrahman-gaber  Hi，gaber,  I thought for several days, and find no solution to solve the problem, can you give a method? How to modify the sample.cpp?

**Comment by whcjb** [comment]
@abdelrahman-gaber  Hi, gaber, have you seccessfully modified the sampler.cpp? I thought for several days, but failed. Could you tell the methods?

**Comment by whcjb** [comment]
[https://github.com/weiliu89/caffe/issues/105#issuecomment-241010747](url)

**Comment by sfzhang15** [comment]
@whcjb 
After obtaining the scale, you shuold judge the shorter size (width or height). The scale for the shorter size is unchanged, but the scale for the larger size should be computed accorrding to the shorter size and its scale.

**Comment by whcjb** [comment]
@sfzhang15  Thanks. In fact, I have done something according to the idea like yours. But it has a bug: In this way, when the normed-bbox multiply the height and width, there will be a square bbox, but the groundtruth bbox will not be Consistency with the square sampled bbox. For example, the original img
w = 100, h=150, so I set the unit_bbox to [0, 0, 1, 2/3], when sampling, the aspect_ratio==1, get a sampled bbox, when the sampled bbox multiply the img w and h, there will be a square img, but the ground truth can not be multiplied to the w and h when Annotransformed. The gt_bbox should be get rid od the 2/3, then can be multiplied to 150, so it will not consistency to the img data, i.e. the squared bbox

Right?

**Comment by whcjb** [comment]
Yes, after thinking again, it's my mistake. Many Thanks

**Comment by DeepakSridhar** [comment]
@sfzhang15 Hi, I don't understand your statement "After obtaining the scale, you should judge the shorter size (width or height). The scale for the shorter size should keep unchanged, but the scale for the larger size should be computed according to the shorter size and its scale."  The bbox size? Also you say that the aspect ratio has no effect but in the sampler.cpp code the random samples are obtained using min and max aspect ratio. what am I missing?

I changed the sampler.cpp so that bbox_width and bbox_height are the same and so the sampled bbox is square?  Is this right?

**Comment by sfzhang15** [comment]
@DeepakSridhar 
Hi, since the bbox_width and bbox_height are normalized by image_width and image_height, respectively, so just keeping bbox_width = bbox_height will not get the square sampled bbox. You need to first unnormalized the bbox_width and bbox_height to unnormalized_bbox_width and unnormalized_bbox_height, then keep unnormalized_bbox_width = unnormalized_bbox_width.

**Comment by DeepakSridhar** [comment]
@sfzhang15 Thanks for your reply! I'll change that

**Comment by loackerc** [comment]
Hi @sfzhang15 sorry to bother, hope you could help with a few questions. I was wondering, just a naive approach, if, we manually cropped the image as square patches outside the network. In this scenario, we have all our square training images (as it does not change the aspect ratio of the image and bounding box).
1) Can we use the cropped square training images as it is? 
2) Does it mean that we basically don't need to modify sampler.cpp?
Many thanks for your help and suggestion!

**Comment by sfzhang15** [comment]
@loackerc 
If you manually cropped the image as square patches outside the network, then you set min_aspect_ratio=1 and max_aspect_ratio=1, it will not need to modify sampler.cpp, but it will loss some randomness.

**Comment by zisianw** [comment]
@sfzang15 thanks for your quick reply and sharing, it’s great to discuss with you!
Sorry, may I know which randomness are you referring to? I think we can still simulate the randomness by randomly generating cropping scales, and randomly sampling the patch location outside the network. Maybe I have missed out something..

**Comment by loackerc** [comment]
@sfzang15 thanks for your quick reply and sharing, it’s great to discuss
with you!
Sorry, may I know which randomness are you referring to? I think we can
still simulate the randomness by randomly generating cropping scales, and
randomly sampling the patch location outside the network. Maybe I have
missed out something..

**Comment by loackerc** [comment]
@sfzhang15 Thanks for your quick reply and sharing, it’s great to discuss with you!!
Sorry, may I know which randomness are you referring to? I think we can still simulate the randomness by randomly generating cropping scales, and randomly sampling the patch location outside the network. Maybe I have missed out something..

**Comment by loackerc** [comment]
@sfzhang15 Indeed.. I missed out the part where SSD cropping the square patches randomly every epoch. Apparently, having random square patches generated every epoch generates more augmentation than just cropping patches externally and re-using same patches every epoch. Thank you for sharing your insight, I definitely benefited from discussing with you.

**Comment by ujsyehao** [comment]
You can directly modify AspectKeepingResizeBySmall() function in im_transforms.cpp
