### ISSUE TITLE
About max_im_shrink in wider test (Cuda memory error)

### ISSUE THREAD

**Issue by ezetl** [sfzhang15/SFD#21]
Hello, while trying to reproduce the results for WIDER FACE I got CUDA memory error.
Exploring a little, I discovered that it is related to the maximum size of the image that Caffe supports.

Currently, the test script for wider sets the shrinking parameter like this:

```
 max_im_shrink = (0x7fffffff / 577.0 / (image.shape[0] * image.shape[1])) ** 0.5
```

I can't find anywhere in Caffe documentation how to get the maximum image size, could you explain what those numbers means? I could run the experiment in my GPU by dramatically reducing `max_im_shrink` but I am not sure how it will affect the final scores if the images are that small.

As a side note, the experiment failed on both 8GB (GTX 1080) and 16 GB (Tesla V100-SXM2) GPUs

Kind regards

**Comment by Edwardmark** [comment]
I met the same error as you,you solved that issue?

**Comment by Edwardmark** [comment]
I solved it by  compiling with cudnn:=1
