### ISSUE TITLE
On computing mAP

### ISSUE THREAD

**Issue by ezetl** [sfzhang15/SFD#22]
This might be a silly question, but could you provide details on how did you compute mAP for WIDER? (Table 3 of the paper). AFAIK one approach could be the proposed in the [Pascal Challenge](http://homepages.inf.ed.ac.uk/ckiw/postscript/ijcv_voc09.pdf) (interpolating precision values from recall values above certain thresholds), but I am not sure if the same methodology was applied in the paper. 

Or did you use the eval_tools provided by WIDER?

Kind regards

**Comment by sfzhang15** [comment]
@ezetl 
We use the eval_tools provided by WIDER

**Comment by ezetl** [comment]
Thank you @sfzhang15
