### ISSUE TITLE
bounding box exceeds image boundary

### ISSUE THREAD

**Issue by loackerc** [sfzhang15/SFD#25]
Hi Shifeng, thank you for the great work on SFD. While I am creating the lmdb for training images, some bounding boxes exceeds the image boundary. 
```
W0416 18:42:23.386387 25345 io.cpp:330] /home/user/Annotations/500017.xml bounding box exceeds image boundary.
W0416 18:42:23.407441 25345 io.cpp:330] /home/user/Annotations/500019.xml bounding box exceeds image boundary.
W0416 18:42:23.433470 25345 io.cpp:330] /home/user/Annotations/500021.xml bounding box exceeds image boundary.
etc....
```

May I know in these cases, do you remove the bounding boxes from lmdb creation? or ignore the warning message. Thank you very much.

**Comment by sfzhang15** [comment]
@loackerc 
When create the lmdb, we use min(max(x,0), img_width) and min(max(y,0), img_height) to limit all bbox in the image.

**Comment by loackerc** [comment]
@sfzhang15, thank you for your sharing! Have a nice day :)
