### ISSUE TITLE
Can not converge

### ISSUE THREAD

**Issue by whcjb** [sfzhang15/SFD#26]
I modified the net struct to be same to your train.prototxt and the modified sampler.cpp and match_bbox.cpp.
Now begin to train, set the lr=0.001 but not converge, always displays NAN. Then change lr to 0.0001. it still NAN. Can you give some instructs? Thank you very much

**Comment by sfzhang15** [comment]
@whcjb 
When does the NAN display? At the first iteration?

**Comment by sfzhang15** [comment]
@whcjb 
What is the value of the first iteration loss? The NAN will display when the scales after norm layers are too large. We set 10 8 6 for conv3_3, conv4_3 and con5_3.

**Comment by whcjb** [comment]
the first iteration loss often up to 20000.
I set the norm according to the paper, i.e. [10, 8, 5, -1, -1, -1]

**Comment by whcjb** [comment]
Thanks， I go to check it

**Comment by whcjb** [comment]
After checking, found it was really the normalizations error, the model is wrong. modified the model, it's OK now. Thanks
