### ISSUE TITLE
Inference phase

### ISSUE THREAD

**Issue by foralliance** [sfzhang15/SFD#28]
@sfzhang15  您好，

在测试时，是按照paper中的参数：

`we first filter out most boxes by a confidence threshold of 0.05 and keep the top 400 boxes before applying NMS, then we perform NMS with jaccard overlap of 0.3 and keep the top 200 boxes.`

还是直接按照deploy.prototxt中的参数：

```
layer {
  name: "detection_out"
  type: "DetectionOutput"
  bottom: "mbox_loc"
  bottom: "mbox_conf_flatten"
  bottom: "mbox_priorbox"
  top: "detection_out"
  include {
    phase: TEST
  }
  detection_output_param {
    num_classes: 2
    share_location: true
    background_label_id: 0
    nms_param {
      nms_threshold: **0.3**
      top_k: **5000**
    }
    code_type: CENTER_SIZE
    keep_top_k: **750**
    confidence_threshold: **0.05**
  }
}
```

貌似paper中的参数（设置的很小（500/200））为了加速用的

**Comment by sfzhang15** [comment]
@foralliance 
文章中那个是inference时的设置，就是实际用的时候；测试的时候就是prototxt那么设置

**Comment by foralliance** [comment]
@sfzhang15 
thanks
