### ISSUE TITLE
Trained model precision on WIDERface 

### ISSUE THREAD

**Issue by whcjb** [sfzhang15/SFD#29]
Hello, Zhang,
I have trained the model according to the setting in the paper, apart from the same prototxts, there are also modied cpp code, including the sampler.cpp and the MatchBBox function, the only difference is the batch size, my is 24, the GPU is K80. After 150k iterations training, using your testing code. Get the score on the hard-set: 83.
I thought for long time, but can't figure out why it is lower than yours which is 85.9.
Could you give some instructions?
Thanks!

**Comment by sfzhang15** [comment]
@whcjb 
Hi, 85.9% is the improved version of SFD and the results in the paper is 85.2% (using old version of eval_tool) and 84.8% (using new version of eval_tool), you can refer to this [issue](https://github.com/sfzhang15/SFD/issues/5) to check these results. Your result (83%) is close to the paper result (84.8%).  is your data augmentation the same as the provided prototxt?
