### ISSUE TITLE
关于faceboxes

### ISSUE THREAD

**Issue by ElegantGod** [sfzhang15/SFD#3]
你好，关于FaceBoxes有几个问题请教下：
1. 论文中在RDCL块都用了bn层，那在MSCL块是否也加了bn层
2.在Inception3后的21个感受野，是不是只要设置3个anchor（32,64,128）就可以了，还有其他操作没

**Comment by sfzhang15** [comment]
@ElegantGod Hi
1. MSCL块也加了bn层
2. Inception3后关联3个anchor（32,64,128）后，还需要对32和64分别进行4倍和2倍的密集化

**Comment by ForestWang** [comment]
关于faceboxes,没有理解anchor密度那块，为什么小的size的密度小（32，64），而大的size密度大（128以上）？在原图上，小的size对应的间隔小，那不是更加密集么？

**Comment by sfzhang15** [comment]
@ForestWang 
我们定义的铺设密度=anchor尺度/anchor铺设间隔，即重叠率
