### ISSUE TITLE
The model_libs.py problem

### ISSUE THREAD

**Issue by whcjb** [sfzhang15/SFD#33]
Hello, Shifeng, sorry abut disturbing you again.

When I check the train.prototxt again, I find the dilation param of your fc6 conv layer is 1, i.e. delation:1.
But when I checking the model_libs.py/VGGNetBody,  according to your setting, I find that the dilation = dilation * 3 ==3,
So, the doubt is： have you changed the formulation to dilation = dilation * 1 ?

Thanks very much.

**Comment by sfzhang15** [comment]
@whcjb 
Yes, we have changed the formulation to dilation = dilation * 1. Besides, according to our experiment, dilation=1 or 3 is not much different.

**Comment by whcjb** [comment]
I see. Thanks very much.
