### ISSUE TITLE
Logic of choosing N

### ISSUE THREAD

**Issue by vaishnavm217** [sfzhang15/SFD#34]
Hi @sfzhang15 ,
In the top- N selection is it safe to assume to take N as 6? All the issues you have mentioned to take it as 6. So for VGG SFD trained on WIDER Face has this parameter as 6 or is there any other logic for it?

**Comment by sfzhang15** [comment]
@vaishnavm217 
Yes, the top-N=6 is the empirically setting for the WIDER Face dataset, since we only have WIDER Face as the training dataset. Besides, as the paper said, we want to set N as the average number from stage one.
