### ISSUE TITLE
Training code release

### ISSUE THREAD

**Issue by AruniRC** [sfzhang15/SFD#35]
Hi, is it possible to release the training source code. The points 2 and 3 in the README are not very precise, and I am not sure of implementing the code exactly as was done in your paper. 
It would make it much easier to compare and modify your SOTA model.

**Comment by sfzhang15** [comment]
@AruniRC Hi,
Sorry about that, my boss do not allow me to release the training code, since he has his own company.

**Comment by zhulinyao** [comment]
Hi, could you please explain it more clearly about the points 2 and 3?

**Comment by zhulinyao** [comment]
@sfzhang15 Hi
Could you please explain it more clearly about the points 2 and 3?
