### ISSUE TITLE
Bug in SFD_trained/deploy.prototxt

### ISSUE THREAD

**Issue by kohenchia** [sfzhang15/SFD#36]
There seems to be a small bug in the trained model's prototxt file.

On `SFD_trained/deploy.prototxt` line 498, convolution layer `fc6` is configured to use `padding: 3`, which is different than `SFD/deploy.prototxt`:
```
layer {
  name: "fc6"
  ...
  convolution_param {
    num_output: 1024
    pad: 3    ### This seems wrong
    kernel_size: 3
  ...
```
and
```
$ diff SFD/deploy.prototxt SFD_trained/deploy.prototxt
498c498
<     pad: 1
---
>     pad: 3
```

This would also cause the feature map dimensions to expand after `fc6`, which is also different than what the paper would suggest.

**Comment by sfzhang15** [comment]
@kohenchia 
Hi, please refer to [this issue](https://github.com/sfzhang15/SFD/issues/9).

**Comment by kohenchia** [comment]
I see. Thank you.
