### ISSUE TITLE
For which reason SSD is needed?

### ISSUE THREAD

**Issue by Mampfi93** [sfzhang15/SFD#39]
Hello together, 

I don't understand why SSD needs to be downloaded to run the S3FD...
can anyone help me out with an explanation?

Thanks in advance!

**Comment by loackerc** [comment]
Hey @Mampfi93,
i) The baseline for SFD is SSD.
ii) SSD is not included in this repo.

**Comment by Mampfi93** [comment]
Hey @loackerc thanks for your answer. Don't know why I missed this information. Now it's clear to me why SSD is needed. Thanks a lot! :)
