### ISSUE TITLE
some questions about ur "Max-out background label"

### ISSUE THREAD

**Issue by takecareofbigboss** [sfzhang15/SFD#4]
i m confused of ur Max-out background label in the paper, where you mean randomly assign each pixel of background different label or according to the type of different pixels, such as tree, bicycle and so on ?

**Comment by takecareofbigboss** [comment]
@sfzhang15

**Comment by sfzhang15** [comment]
@takecareofbigboss 
The max-out background label predicts the non-face score several times and then select the max score as the final non-face score so as to reduce the false positive rate of face. We do not assign the type of different pixels, such as tree, bicycle and so on.
