### ISSUE TITLE
Changes necessary?

### ISSUE THREAD

**Issue by Mampfi93** [sfzhang15/SFD#40]
Hello together,
I'm running SFD inside a Docker Container. To run wider_test.py I had to make the following changes:
L. 10,11
>
    # import sys
    # sys.path.insert(0, 'python')

L. 138
>
    change:
    model_weights = caffe_root + '/models/VGGNet/WIDER_FACE/SFD/SFD.caffemodel'
    to:
    model_weights = caffe_root + '/models/VGGNet/WIDER_FACE/SFD_trained/SFD.caffemodel'

L. 160
>
    change:
    Image_Path = Path + im_name[:] + '.jpg'
    to:
    Image_Path = Path + event[0][0] + '/' + im_name[:] + '.jpg'

Now my questions are:
Did anyone face this issue two? Or did I just catch an old version of wider_test.py?
Why did I have to deactivate the part with "import sys"?

Any help is appreciated. Thanks in advance!

**Comment by sfzhang15** [comment]
@Mampfi93 
1. The first change is ok, if you deactivate this and it can run successfully
2. We have updated the provided model path. You change is right.
3. The original dataset put images into different folders according to different events, but we put all images into one folder. You change is right for the original dataset.

We have updated the wider_test.py.

**Comment by Mampfi93** [comment]
@sfzhang15 
Thanks for your response. :)
I think we can now close this issue. ;)
