### ISSUE TITLE
Bounding boxes with negative x-values

### ISSUE THREAD

**Issue by Mampfi93** [sfzhang15/SFD#41]
Hello together, 
while testing the sfd I recognized that some bounding boxes x-values are negative.
Am I the only one facing this issue?
Could the reason be the mapping of the different sized pictures while detection?

Any help appreciated! Thanks in advance. :)

**Comment by sfzhang15** [comment]
@Mampfi93 
Some pre-set anchors are outside the image, which may result in some output bounding boxes x-values are negative.

**Comment by Mampfi93** [comment]
Ah okay, good to know. Thanks again for your quick answer! :)
