### ISSUE TITLE
Change Anchor Boxes Aspect Ratio

### ISSUE THREAD

**Issue by ahkarami** [sfzhang15/SFD#43]
Dear @sfzhang15,
As you have mentioned in your paper `Our anchors are 1:1 aspect ratio (_i.e.,_ square anchor)`, the aspect ratios of all anchor boxes are 1:1. However, if one wants to change the aspect ratios of anchor boxes for example, to 1:1.4 (width:height) the network structure must be changed or just the _training code_ & _decoding strategy_ must be changed? Would you please explain how one can change the aspect ratios of anchor boxes?

**Comment by sfzhang15** [comment]
@ahkarami 
The network structure do not need to change. If you want to change the aspect ratio, you can directly change it from 1:1 to 1:1.4 at the prototxt, then retrain the model.

**Comment by ahkarami** [comment]
@sfzhang15,
Thank you for your answer. 
If you are familiar with _PyTorch_ I have just one another question. As you now there is a third-party implementation of your code on [PyTorch](https://github.com/clcarwin/SFD_pytorch). If one wants to apply above mentioned changes (_i.e.,_ changing anchor boxes aspect ratios for training process), then the [_decoding strategy_](https://github.com/clcarwin/SFD_pytorch/blob/96fdfbe22eef176a04802d915834b82a131a854d/bbox.py#L77) must be changed?

**Comment by sfzhang15** [comment]
@ahkarami 
I think the decoding strategy does not need to change.

**Comment by ahkarami** [comment]
Thank you very much.
