### ISSUE TITLE
pacal faces

### ISSUE THREAD

**Issue by foralliance** [sfzhang15/SFD#44]
@sfzhang15 HI!
能否给一个具体的Pascal face数据集具体的下载地址．您给的链接是Pasacal数据集的链接！
麻烦了！

**Comment by sfzhang15** [comment]
@foralliance 
Pascal face是Pasacal的一部分图片

**Comment by foralliance** [comment]
@sfzhang15 
了解了，简单的合并了voc12的训练集和测试集，配合着您提供的pascal_img_list.txt文件，实现了检测！！

还有一个问题：
在检测工具**EVALUATION TOOLBOX**中，在`plot_AP.py`中，有2个参数`ovr`和`is_point`，发现**这2个参数需要根据检测方法的不同而改变**．因为没有仔细看源码，麻烦您能简单解释下这2个参数的含义吗？还有什么情况下需要改变？？

**Comment by sfzhang15** [comment]
@foralliance 
那个是针对某些比较老的检测算法，不用管

**Comment by foralliance** [comment]
@sfzhang15 
many thanks!!!
