### ISSUE TITLE
FDDB test

### ISSUE THREAD

**Issue by foralliance** [sfzhang15/SFD#45]
@sfzhang15 HI

关于FDDB的结果，用您的模型得到的结果如下：
1表示：新标签，没转换椭圆，DiscROC=0.982252，ContROC=0.75709
2表示：旧标签，没转换椭圆，DiscROC=0.979888，ContROC=0.754134 
3表示：新标签，已转换椭圆，DiscROC=0.982437，ContROC=0.855419 
4表示：旧标签，已转换椭圆，DiscROC=0.979888，ContROC=0.848032
以上结果均基于 FalsePositive=1000

在#5 中，关于FDDB的结果也给出了详细的讨论，

有1个问题：
网络一般输出的都是rectangle box，是不是在递交检测结果之前，都需要将网络的rectangle box转换为ellipse box？？

**Comment by sfzhang15** [comment]
@foralliance 
对离散影响不大，对连续影响很大，这个转不转，看个人选择，都可以的

**Comment by foralliance** [comment]
@sfzhang15 
了解了！！麻烦了！
