### ISSUE TITLE
questions about the anchor matching

### ISSUE THREAD

**Issue by pobei** [sfzhang15/SFD#46]
hi, 
     I am now reproducing the paper, and now confused about the section **3.2. Scale compensation anchor matching strategy** in your paper. 
    the paper says that at stage two,
>  **firstly picking out anchors whose jaccard overlap with this face are higher than 0:1, then sorting them to select top-N as matched anchors of this face. We set N as the average number from stage one.**
  
     I think chances are that some anchor may match more that one face bounding boxes, how do you deal with this.
    And the other question is the matched anchor at stage two may include the anchors matched  at stage one,  i want to know how you select the top-N matched anchors at stage two.
                                                                                                                               thanks

**Comment by pobei** [comment]
Emmm. And i also wonder that your  "Scale compensation anchor matching strategy"  is applied on all feature maps or just conv3_3 ?  thanks

**Comment by sfzhang15** [comment]
@pobei 
1. "how do you deal with these anchors that match more than one face bounding boxes": we use a variable to record the best match gt for each anchor.
2. "the matched anchor at stage two may include the anchors matched  at stage one": when matching anchor at stage two, we will judge if the anchor has been matched at stage one and we only match these anchors that do not be matched at stage one.
3. "Applied on all feature maps or just conv3_3": no, we apply on all layers.

**Comment by pobei** [comment]
@sfzhang15  
                thanks for your reply！
