### ISSUE TITLE
Evaluating of FDDB

### ISSUE THREAD

**Issue by pittyacg** [sfzhang15/SFD#47]
Hello. I am trying to evaluate the code on the datasets proposed, but the evaluation on FDDB gives errors like "Line #33380 (got 6 columns instead of 1)" even after changing the format using the matlab script provided.

Do you have any idea why is this happening and how can it be solved?

Thank you!

**Comment by sfzhang15** [comment]
@pittyacg 
I am not sure where the problem is. Maybe the output format is wrong. Are you using the test files we provided?
