### ISSUE TITLE
question about multi-scale testing

### ISSUE THREAD

**Issue by pobei** [sfzhang15/SFD#48]
hello, 
            when you apply multi-scale testing,  how do you change the anchor setting , for example, the input size is twice as the size of training, I double the size of feature maps (generating anchors), to ensure the number of anchors is equal to the number of channels of the network,  however, i have tried both remaining  the setting of  ''min_size'' and double the value of "min_size" , they all do not work well(map drops a lot),

**Comment by sfzhang15** [comment]
@pobei 
We have released [all testing code](https://github.com/sfzhang15/SFD/blob/master/sfd_test_code/WIDER_FACE/wider_test.py).

**Comment by foralliance** [comment]
@pobei  HI
"`ensure the number of anchors is equal to the number of channels of the network`",what does that mean?

Why change anchor setting? Although scaling leads to larger feature maps. However, I think **the setting of anchor should not change no matter how the test scale changes**.

**Comment by sfzhang15** [comment]
@foralliance  
I agree with your opinion. The testing codes have been released, I suggest @pobei to review the code.
