### ISSUE TITLE
balance the loss of classification and regression

### ISSUE THREAD

**Issue by cassie101** [sfzhang15/SFD#49]
```
  multibox_loss_param {
    loc_loss_type: SMOOTH_L1
    conf_loss_type: SOFTMAX
    loc_weight: 1.0
    num_classes: 2
    share_location: true
    match_type: PER_PREDICTION
    overlap_threshold: 0.35
    use_prior_for_matching: true
    background_label_id: 0
    use_difficult_gt: true
    neg_pos_ratio: 3.0
    neg_overlap: 0.35
    code_type: CENTER_SIZE
    ignore_cross_boundary_bbox: false
    mining_type: MAX_NEGATIVE
  }
}
```
In the paper, "lambda= 4 to balance the loss of classification and regression." May I know where do you set lambda = 4? do we set  loc_weight: 1.0 to 0.25?
Or modify conf in multibox_loss_layer.cpp?
Thank you~

**Comment by sfzhang15** [comment]
@cassie101 
The classification loss in [SSD](https://github.com/weiliu89/caffe/blob/ssd/src/caffe/layers/multibox_loss_layer.cpp#L248-L251) is divided only by the number of positives. Since neg_pos_ratio=3.0, it  is equivalent to the classification of the loss multiplied by a 4.

**Comment by cassie101** [comment]
got it, thanks
