### ISSUE TITLE
FDDB lower detection accuracy

### ISSUE THREAD

**Issue by whcjb** [sfzhang15/SFD#5]
Hi, zhang
I use your caffe model test on the FDDB datasets, got DiscROC=95.0 detection accuracy rate at the FalsePositive=400,
but you give a 98.3 on the paper, can you give a reason?
![ypfsfdofidiscroc](https://user-images.githubusercontent.com/11767995/32872142-1e259314-cac0-11e7-8b7a-87fd924fb10e.png)

**Comment by zhangyunming** [comment]
the caffemodel release maybe not the best of author

**Comment by zhaoyuanxing** [comment]
do you use the face label provided by the author?

**Comment by whcjb** [comment]
no, I use the official eval-code and image list

**Comment by whcjb** [comment]
I also test on Widerface, only got 58.1 of the hard val set.
the model name on the picture is SFD-OFFICIAL

**Comment by whcjb** [comment]
You release a rubbish model?
**# Where is the base trust among people？**

**Comment by sfzhang15** [comment]
@whcjb 
Do you use our sfd_test_code to test?

**Comment by sfzhang15** [comment]
@zhangyunming 
The caffemodel release is our model used for the paper. All the results of the paper can be got by this model and our test code.

**Comment by sfzhang15** [comment]
@whcjb @zhangyunming @zhaoyuanxing 
The following is the latest results that are got by our sfd_test_code and our provided model:
![image](https://user-images.githubusercontent.com/31090111/32883244-c9492d06-caf1-11e7-9935-fb4b130e3c13.png)

![image](https://user-images.githubusercontent.com/31090111/32883285-e32a6b36-caf1-11e7-971c-f7c9fc3e6978.png)

![image](https://user-images.githubusercontent.com/31090111/32883307-f99f4206-caf1-11e7-8fb8-d874a0c458f3.png)

**Comment by sfzhang15** [comment]
@whcjb @zhangyunming @zhaoyuanxing 
We are running the WIDER FACE test code now. Later, We will provide the test results on WIDER FACE val set.

**Comment by whcjb** [comment]
I use your test code apply on the FDDB datasets, got DiscROC=**96.6** detection accuracy rate at the FalsePositive=400,

**Comment by sfzhang15** [comment]
@whcjb 
The 98.3 is at the FalsePositive=1000 with our new annotation. Your result (without our new annotation) is right: 96.6 at fp=400 and 98.0 at fp=1000.

**Comment by sfzhang15** [comment]
@whcjb @zhangyunming @zhaoyuanxing 
Here is the lastest results on WIDER FACE val set, which are got via using our provided model and the old/latest version evaluation tool.
![image](https://user-images.githubusercontent.com/31090111/32888004-d608051c-cb00-11e7-84c9-9e86e7ba4e2c.png)

**Comment by sfzhang15** [comment]
The evaluation tool of WIDER FACE has slightly changed around March. The annotation (i.e., gt_list) used for the evaluation is slightly changed. So there are is a slight difference between the results got from the old and the latest version of evaluation tool.
