### ISSUE TITLE
pascal face dataset

### ISSUE THREAD

**Issue by songyaqi** [sfzhang15/SFD#51]
Dear @sfzhang15 how can I get pascal face dataset ? I can't find it .Thank you for your time

**Comment by sfzhang15** [comment]
@songyaqi 
The pascal face dataset is a subset of pascal dataset, you should download it.

**Comment by songyaqi** [comment]
Thank you for your time and response

> @songyaqi
> The pascal face dataset is a subset of pascal dataset, you should download it.
Thank you for your time and response

**Comment by fengyuentau** [comment]
@songyaqi Did you find the annotation files for PASCAL Face? I cannot find it anywhere on the Internet.
