### ISSUE TITLE
Any progress in learning multiple background classes?

### ISSUE THREAD

**Issue by yijunCai** [sfzhang15/SFD#55]
Hi @sfzhang15 
Thanks for sharing your work!
I've had a similar idea of learning multiple background classes with max-out and other constraints, but I found it hardly worked (brought no notable improvement) for pedestrian detection. I'm still interested in this idea though, and I'm wondering if you have any progress on it?

**Comment by sfzhang15** [comment]
@yijunCai 
Hi, we only use the max-out on the lowest detection layer that associated with lots of small anchors. And as you can see in the paper, the improvement of max-out is relatively slight.
