### ISSUE TITLE
fpn out of memory

### ISSUE THREAD

**Issue by EchoIR** [sfzhang15/SFD#56]
您好，我加入fpn之后测试到中间的某一张图，出现out of memory, 可能是需要新的max input size计算公式，我想问一般是如何计算这个max input size的，另外，“Hi, the blob max_size is 0x7fffffff. As for VGG16, the biggest blob appear on CONV1_2‘s bias term, which blob size is (num-channel * kennel-size * kennel-size) * img-height * img-width = (64x3x3) * img-height * img-width = 576 * img-height * img-width”，我不懂 (num-channel * kennel-size * kennel-size) * img-height * img-width是如何都得到的？

**Comment by sfzhang15** [comment]
@EchoIR 
1. 你可以把一个图片risize到指定尺寸，看看不超显存的情况下，最大尺寸是多少，然后别的图的最大缩放系数就根据这个最大尺寸来算。
2. 那个应该是根据前传中出现最大blob算的，最大blob应该是出现在im2col，比如3x3的卷积核对64x640x640featuremap进行卷积时，im2col会搞成一个(64x3x3)x640x640的blob，这个应该是最大的blob了。

**Comment by EchoIR** [comment]
特别感谢🙏，我试试


| |
王素娟
邮箱：sjwang_echo@163.com
|

签名由 网易邮箱大师 定制

On 11/19/2018 18:22, Shifeng Zhang wrote:

@EchoIR

你可以把一个图片risize到指定尺寸，看看不超显存的情况下，最大尺寸是多少，然后别的图的最大缩放系数就根据这个最大尺寸来算。
那个应该是根据前传中出现最大blob算的，最大blob应该是出现在im2col，比如3x3的卷积核对64x640x640featuremap进行卷积时，im2col会搞成一个(64x3x3)x640x640的blob，这个应该是最大的blob了。

**Comment by yxlijun** [comment]
您好，请问在训练的时候输入图片是resize到640还是直接按照原图或原图的ratio进行训练啊？
