### ISSUE TITLE
Question about evaluation resolution.

### ISSUE THREAD

**Issue by casperthuis** [sfzhang15/SFD#58]
Hi @sfzhang15
Thanks for sharing your work!

I had a question about the evaluation code you provided.  The first evaluation on the image has a comment with original test. 

```
det0 = detect_face(net, image, shrink)  # origin test
```

Is this test is performed on the original resolution of the image or the original resolution of the network(640*640)? If the test is performed on the original resolution of the image, do you just take the shortest side of the image and then make it square or do you take a resolution that fits better with the network?

Hope you have the time to answer my questions.

Thank you in advance.

**Comment by sfzhang15** [comment]
@casperthuis 
The first evaluation is tested with the original image without any reszie operation. But several images in WIDER FACE are very large and can not be tested with the original size. As for these images, we proportionally resize them to the largest size that GPU can take in.

**Comment by casperthuis** [comment]
@sfzhang15  Thank you for the quick answer.
