### ISSUE TITLE
The annotated smallest face in wider face

### ISSUE THREAD

**Issue by LeileiCao** [sfzhang15/SFD#59]
Shifeng,您好,
向您请教一个问题.Wider face数据集那篇论文中说忽略了10以下像素的人脸,但实际训练集和验证测试集中都有标注10像素以下的小人脸.是后来标注了呢?还是什么?

**Comment by sfzhang15** [comment]
@LeileiCao 
WIDER FACE应该是所有脸都标了，只是太小或太困难的，会置为invalid。

**Comment by LeileiCao** [comment]
我注意到训练集和验证集中最小标注人脸尺寸2个像素.训练的时候需要对数据做清洗吗?去除这些小人脸吗?

**Comment by sfzhang15** [comment]
@LeileiCao 
是的，训练时太小的人脸可以忽略的

**Comment by LeileiCao** [comment]
好的,谢谢您
