### ISSUE TITLE
when trained the model

### ISSUE THREAD

**Issue by zhangyunming** [sfzhang15/SFD#6]
hi zhang

i trained the model use your train.prototxt on original ssd,  there is no bug, but you said :

Modify the data augmentation code of SSD to make sure that it does not change the image ratio.

Modify the anchor match code of SSD to implement the 'scale compensation anchor matching strategy'.

how to modify the code,can you give your code modified based on ssd?

**Comment by sfzhang15** [comment]
Without modify the code, it also can run, but the data augmentation will change the image ratio, which makes the ratio of face deviate from 1:1. In addition, the scale compensation anchor matching strategy is not used. You can modify the 'SampleBBox' and 'MatchBBox' functions to implement them.

**Comment by zhangyunming** [comment]
if not modify the code ,the mAP will reduce？ can you give the code you modified?

**Comment by sfzhang15** [comment]
Probably yes. You can complete your training and test the trained model.
Sorry about that.

**Comment by takecareofbigboss** [comment]
@zhangyunming  i have used the code not modified, and pretrained by VGG16.caffemodel. The result is bad. Now, i train it again using VGG_ILSVRC_16_layers_fc_reduced.caffemodel, you can wait till tmr, i will show u my results.

**Comment by takecareofbigboss** [comment]
@sfzhang15  could u plz tell me ur results on widerface without modification.
A little strange is that the training process is very slow.

**Comment by takecareofbigboss** [comment]
![image](https://user-images.githubusercontent.com/11883059/33264999-ce56bf2c-d3aa-11e7-94e4-e66ccad1ac03.png)

**Comment by sfzhang15** [comment]
@zhangyunming  Hi, sorry. We do not train our model using the code without modification. All the trained models at least are applied the modification of data augmentation. As for the anchor matching strategy, you can refer to the results in the Table 3. 
As for the training time, with 2 Titan X GPUs, the training speed is about 4s per iteration in our server.

**Comment by sfzhang15** [comment]
@takecareofbigboss Without the modification of data augmentation code, the GT face box may be away from 1:1, and the ratio of our anchor is 1:1, so it will hurt the performance.
According to your screenshots, you run caffe code on the debug model? The time-consuming is mainly in reading lmdb.

**Comment by takecareofbigboss** [comment]
yep, i use debug mode.  hope you can give ur results of the trained models applied on the modification of data augmentation.

**Comment by sfzhang15** [comment]
@takecareofbigboss The results of only appiled the modification of data augmentation is listed in the Table 3 in our paper, i.e., SFD(F)

**Comment by takecareofbigboss** [comment]
ok, maybe i should cancel debug mode, and use the normal mode. thks.

**Comment by takecareofbigboss** [comment]
i changed it into normal mode, and the process time seems normal too.  thank you

**Comment by abdelrahman-gaber** [comment]
@takecareofbigboss  Did you manage to train the model without any modifications, what was the results you get on wider_face ?

**Comment by foralliance** [comment]
@sfzhang15 
'SampleBBox' and 'MatchBBox' functions 

Where are these two functions?
