### ISSUE TITLE
widerface test of bbox_vote

### ISSUE THREAD

**Issue by yja1** [sfzhang15/SFD#60]
when test on widerface,run wider_test.py 
in function bbox_vote,when detect none face in image:there is error:
dets = dets[0:750, :] UnboundLocalError: local variable 'dets' referenced before assignment

so I change that,if dets is none , fout.write('0\n'),right?

but result is low compare to paper

**Comment by sfzhang15** [comment]
@yja1 
If detections from all scales are empty, you can change it as you said.
Do your use our provided model to test?

**Comment by yja1** [comment]
thank you
no. I test another code DSFD. wider_test.py same with your code.
