### ISSUE TITLE
SFD中有过滤特别小的人脸么

### ISSUE THREAD

**Issue by luuuyi** [sfzhang15/SFD#62]
如题，感谢回复

**Comment by luuuyi** [comment]
不好意思，继续补充一下，我目前基于Faceboxes.Pytorch复现论文的结果较差，大概只有71左右，仔细读了几遍论文和你在这个repo下面的回复，唯一的区别是我没有过滤小于6的small face，看到你在有一个问题下面回复说如果不过滤小人脸，会很难训练或者需要更多的small anchor进行匹配，这部分差异会不会就是导致性能下降的主要原因？感谢回复

**Comment by sfzhang15** [comment]
@luuuyi 
训练中过滤了长或宽小于6个像素的gt，但是这个影响不会很大。

**Comment by luuuyi** [comment]
@sfzhang15 感谢回复

**Comment by luuuyi** [comment]
不好意思，我继续求证一个问题，其实基于FaceBox的pytorch版本复现SFD到现在，基本上论文里面明确的东西都对应上了。hard始终在75左右，跟 #57 提问者遇到的情况一样，我后面咨询了他，他在你论文基础上增加了data anchor sampling才达到85的结果。所以我有两个问题，在数据采样和data augmentation部分，Faceboxes和SFD除了过滤小人脸的尺寸不一样，resize尺寸不一样之外还有区别么？论文中是否用到了其他的策略比如data anchor sampling这种

**Comment by luuuyi** [comment]
我好像看到一个忽略的地方了，Faceboxes用了1024x1024作为输入，所以没有expand操作，而如果作者您的data augmentation继承自SSD的话，应该是先做了一个1倍到4倍的random expand，该操作其实并没有改变图像中人脸尺寸的大小，对于expand出来的区域使用均值填充，这样做了以后进行[0.3, 1] 的 random crop在缩小到640x640，就可以获得更多地小人脸样本，也能达到data anchor sampling的目的，我这样理解对么

**Comment by luuuyi** [comment]
我好像看到一个忽略的地方了，Faceboxes用了1024x1024作为输入，所以没有expand操作，而如果作者您的data augmentation继承自SSD的话，应该是先做了一个1倍到4倍的random expand，该操作其实并没有改变图像中人脸尺寸的大小，对于expand出来的区域使用均值填充，这样做了以后进行[0.3, 1] 的 random crop在缩小到640x640，就可以获得更多地小人脸样本，也能达到data anchor sampling的目的，我这样理解对么
