### ISSUE TITLE
Out of memory on both GPU and CPU modes with a single 400 * 300 image

### ISSUE THREAD

**Issue by bdalal** [sfzhang15/SFD#63]
Hi @sfzhang15 
I'm using wider_test.py implementation to test on a 400 * 300 image but I run out of memory on both the GPU and in CPU mode for the `multi_scale_test`.
I went over the other issues and it seems like 2GB memory for the graphics card is too little. I have a 940MX.
However, I've got 16GB of memory with more than 15GB available at the time of running my test on cpu mode but I can still my memory blow upto more than 15GB at which point my computer freezes.

I also tried on a 32GB machine in CPU only mode and ran out of memory again.

So I have a couple of questions:
1) Do you know if an image this small should end up consuming so much memory?
2) Do you know of any way I can troubleshoot this memory blowup in case an image this size shouldn't take up so much memory?

Thanks a lot for your feedback!

**Comment by sfzhang15** [comment]
@bdalal 
1. Regardless of the original size of the input image, multi-scale testing will continuously scale it up to the largest size.
2. We do not test the model on CPU mode, so we don't know how much memory it actually needs. If you don't have enough GPU memory, you can try to reduce [this hyper-parameter](https://github.com/sfzhang15/SFD/blob/master/sfd_test_code/WIDER_FACE/wider_test.py#L162) and the performance will drop.

**Comment by bdalal** [comment]
Thanks for your prompt response Shifeng! I'll give (2) a shot.
