### ISSUE TITLE
Reason for difference in test codes of Wider vs FDDB

### ISSUE THREAD

**Issue by bdalal** [sfzhang15/SFD#64]
Hi,
I noticed that for the Wider dataset, the image is getting resized multiple times and being run through the detector while this is not the case for FDDB. The image is directly run through the net.
For AFW and PASCAL on the other hand, it is resized to 640px.

Is this because Wider contains pictures with many (possibly small) faces where as FDDB is mostly individuals or few people with large faces in the pictures?

If this is the case, how do you suggest the test code be adapted to run with a custom dataset? Should it use the Wider heuristic of resizing if there are many people or resize the image to a particular resolution?

Thank you!

**Comment by sfzhang15** [comment]
@bdalal 
A trained face detector has its own optimal detection range of face scales, you'd better resize the faces of the testing images in this range for better performance.
For single-scale testing on AFW, PASCAL Face and FDDB, these datasets are relatively easy and single-scale testing is enough. These single-scale testing scales are selected via experiments accoding to the above rule.
For multi-scale testing on WIDER FACE, this dataset has lots of tiny faces that need multi-scale testing to improve the performance.

**Comment by bdalal** [comment]
I Understand. Thanks for clearing this up!
