### ISSUE TITLE
Suggested confidence threshold to detect faces and minimize false positives

### ISSUE THREAD

**Issue by PranayPasula** [sfzhang15/SFD#65]
Hi,

Based on your testing, is there a confidence score threshold that would be sufficient to detect most faces while avoiding most false positives?

From a few examples, it seems like a threshold of 0.5-0.6 is promising.

**Comment by sfzhang15** [comment]
@helloworldexpert 
For evaluation on the testing set, the lower confidence score threshold is better. For practical applications, the confidence score threshold is set  according to different scenarios, generally around 0.7.

**Comment by PranayPasula** [comment]
@sfzhang15 Thank you!
