### ISSUE TITLE
inference time of the detect face

### ISSUE THREAD

**Issue by zhukkang** [sfzhang15/SFD#66]
thanks for your nice work and share~

i have done the test on  TITAN Xp  and 1080 GPU with the python script, but VGA input got almost 300 ms , can you help to guide how can got the 36 FPS describe in the paper, is there anything need change ?

**Comment by sfzhang15** [comment]
@wangnet 
We use the [caffe time](http://tutorial.caffe.berkeleyvision.org/tutorial/interfaces.html) to measure the speed for VGA.
