### ISSUE TITLE
The implementation details of stage two of compensation matching strategy

### ISSUE THREAD

**Issue by sagittahjz** [sfzhang15/SFD#68]
When I attached stage two of compensation matching strategy to my pytorch project, I used a for loop, and it will iterate at most all anchors (about 30000 times for a 640 * 640 input image).
Consequently it cost about 4X time in training than before.

Can you give me some hints about a more efficient implementation?

**Comment by sfzhang15** [comment]
@sagittahjz 
If you use pytorch, you can try to use array operations that may be more efficient.

**Comment by sagittahjz** [comment]
More specificly, do operations to the whole tensor, and use mask to select the element in it can be more efficient.
