### ISSUE TITLE
about eval_tools for widerface

### ISSUE THREAD

**Issue by NickMinYang** [sfzhang15/SFD#7]
@sfzhang15 
what does "gt_list" in "wider_easy_val.mat" mean?

**Comment by sfzhang15** [comment]
@NickMinYang Hi, eval_tools is downloaded from the official website of WIDER FACE dataset (http://mmlab.ie.cuhk.edu.hk/projects/WIDERFace/). The gt_list means which GTs are used for evaluation.

**Comment by NickMinYang** [comment]
@sfzhang15 
Ok,thanks!
By the way, is there any documentation for the eval_tools?

**Comment by sfzhang15** [comment]
Maybe not. Perhaps you can refer to their paper.

**Comment by NickMinYang** [comment]
Ok,thanks!

**Comment by NickMinYang** [comment]
@sfzhang15 
Not all GTs are used for evaluation???
For example, there are many faces in pic "0_Parade_marchingband_1_465.jpg",
but only 31,32,125 are used for hard, and none is used for easy and medium?

**Comment by sfzhang15** [comment]
In my opinion, yes. There are some extremely tiny faces (e.g., ≤ 5 pixels) that are not used for evaluation. If you want to confirm that, you can contact the author of WIDER FACE dataset.

**Comment by NickMinYang** [comment]
@sfzhang15 
Ok! Thank you very much for you reply!

**Comment by NickMinYang** [comment]
From the paper and .mat，I think tiny faces(height < 10 pixels) are not used for evaluation。
But when training，do you use these tiny faces?

**Comment by sfzhang15** [comment]
@NickMinYang 
When training，we do not use these extremely tiny faces (i.g., width or height＜6 pixels).

**Comment by marvis** [comment]
Hi @sfzhang15 ,

I can't find any code which filters extremely tiny faces (width or height < 6). Can you tell me the place of these codes? 

Great Job! Thanks!

**Comment by sfzhang15** [comment]
@marvis Hi, you can modify the MeetEmitConstraint function in bbox_util.cpp to filter extremely tiny faces.
