### ISSUE TITLE
Message type "caffe.LayerParameter" has no field named "norm_param".

### ISSUE THREAD

**Issue by youthM** [sfzhang15/SFD#71]
I met the following problem :
[libprotobuf ERROR google/protobuf/text_format.cc:274] Error parsing text-format caffe.NetParameter: 684:14: Message type "caffe.LayerParameter" has no field named "norm_param".
WARNING: Logging before InitGoogleLogging() is written to STDERR
F0917 20:55:40.472899  3642 upgrade_proto.cpp:79] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: model//SFD_trained//deploy.prototxt
*** Check failure stack trace: ***

**Comment by kedardg** [comment]
How did you solve this issue?

**Comment by aswin-datakalp** [comment]
@youthM , can you plz let me know how did you solve this ?

**Comment by dibet** [comment]
same problem!!
