### ISSUE TITLE
about receptive field

### ISSUE THREAD

**Issue by foralliance** [sfzhang15/SFD#72]
@sfzhang15 
你好！！
在S3FD的Table1．6个Detection Layer对应的感受野分别是48,108,228,340,468,724．

想明确的一点是：这6组感受野应该是这6个层经过**Figure2中Predicted Convolutional Layers部分的3*3卷积层**后的感受野吧．
比如，在VGG16中，conv3_3的感受野应该是40，经过**Figure2中Predicted Convolutional Layers部分的3*3卷积层**后，感受野才是44．

不知道自己的理解是否正确？？

**Comment by sfzhang15** [comment]
@foralliance 
表格中的感受野，是检测层上3*3区域对应的感受野，因为每个检测层后面都是跟的3*3的卷积核进行的预测。

**Comment by foralliance** [comment]
@sfzhang15 
那就是这6组感受野确实不是VGG16中６个层的感受野，而是这６个层分别加1个3*3卷积层后的感受野．

**Comment by sfzhang15** [comment]
@foralliance 
嗯，可以理解为6个层上3*3的感受野，或者6个层后面加了个3*3的卷积层，这个层上1*1的感受野。

**Comment by foralliance** [comment]
@sfzhang15 
了解了！！谢谢
