### ISSUE TITLE
How to set max-out groundtruth in training?

### ISSUE THREAD

**Issue by chenpengf0223** [sfzhang15/SFD#74]
@sfzhang15 
Thanks for sharing your great work.
I have some confusion about the 'max-out' background label, for example I use Nm=3, the groudtruth of the label should be "0, 0, 0, 1"for positive example, and "1, 1, 1, 0" for negative example?
If there is the process in the code?

**Comment by sfzhang15** [comment]
@chenpengf0223 
 The max-out operation first outputs four channels, then uses max eltwise opeation to output two channels. Thus, the ground-truth label does not need to change, which is the same as the original set. Please download our trained model and prototxt for more details.
