### ISSUE TITLE
你好，想请教一个priors num不match confidence number的问题

### ISSUE THREAD

**Issue by jhgfkdj** [sfzhang15/SFD#75]
这个问题困扰我好几天了，因为我也是做的人脸的二分类，只是我把backbone换成了mobilenet。后面的这个priorsbox跟location跟confidence的所有params都是按照你的来的没有改变。但是总是报错Check failed: num_priors_ * num_classes_ == bottom[1]->channels() (2730 vs. 4778) Number of priors must match number of confidence predictions.我实在是搞不懂是哪里没匹配上了，请教一下。

**Comment by jhgfkdj** [comment]
@sfzhang15 好像我搞定这个问题了，我按照自己的思路来写的话，就是跟你的唯一不同在于我把conv3_3_norm_mbox_conf层的num_output改为了2， 就跑通了，不知为何你的是4？

**Comment by sfzhang15** [comment]
@jhgfkdj 
因为使用了背景标签最大化操作max-out，所以conv3_3_norm_mbox_conf层的num_output是4。

**Comment by jhgfkdj** [comment]
> @jhgfkdj
> 因为使用了背景标签最大化操作max-out，所以conv3_3_norm_mbox_conf层的num_output是4。

oh so it is! 我的确没用max_out层，了解了，多谢你！
