### ISSUE TITLE
padding size of fc6

### ISSUE THREAD

**Issue by marvis** [sfzhang15/SFD#9]
Hi @sfzhang15 ,

I just found that the padding size of fc6 is 3, which will cause the feature map of fc7 to be 24x24 instead of 20x20 (as paper described). I am curious whether this will affect the matching between prior box  and ground truth?

Best,

**Comment by sfzhang15** [comment]
@marvis Hi, nice question. It's a negligible mistake for this model. Some prior boxes go beyond the boundaries of the image and will never be matched (no effect). We have trained the model with pad=1 and its results is almost the same as this model. The train.prototxt is also updated. Thanks.

**Comment by foralliance** [comment]
@sfzhang15 
when fc7 to be 24x24 instead of 20x20, why "Some prior boxes go beyond the boundaries of the image and will never be matched"??

**Comment by sfzhang15** [comment]
@foralliance 
Since for every detection layer,  it has a fixed parameter 'step'. As for the fc7, its step is  32. So 24x24 will result in some anchor out of the image, i.e., 0, 32, 64,....., **640, 672, 704, 736** (out of image).

**Comment by foralliance** [comment]
@sfzhang15 
many thanks
